FROM java:8-jdk-alpine
COPY ./target/ephs-eureka-server-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app
RUN sh -c 'touch ephs-eureka-server-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java","-jar","ephs-eureka-server-0.0.1-SNAPSHOT.jar"]
